### ISSUE TITLE
Samsung ML-2164

### ISSUE THREAD

**Issue by Tiger862000** [OpenPrinting/printing-stack-snap#5]
hi, first thank you for developing this snap. it enables you to build a small sleek system to add wireless printing functionality to USB printers.

now to my questions: 
Is there a way to get Samsung ML2160 Version in specific ML-2164 to work?

**Comment by tillkamppeter** [comment]
The printing stack snap itself only supports printers which do driverless IPP printing (AirPrint, IPP Everywhere, Mopria Wi-Fi Direct Print) and some legacy PostScript and PCL printers, but there is a framework under development which allows making snaps of common classic printer driver packages, like HPLIP, Gutenprint, SpliX (the one which you would need), ... See
https://github.com/dheeraj135/Printer-Applications-Framework
and
https://github.com/dheeraj135/Printer-Application-Snaps

**Comment by Tiger862000** [comment]
Thank you! I will take a look at it. Hope there is ARMv7 compatible driver for that printer...
